### ISSUE TITLE
Android camera crashes on some devices (1.4.0)

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-mobile#464]
Here is the full stack for the android camera error.

```
# Crashlytics - plaintext stacktrace downloaded by Abdullah Almsaeed at Thu, 12 Jul 2018 00:47:58 GMT
# URL: https://fabric.io/treesnap2/android/apps/com.treesource/issues/5b465b2b6007d59fcd4084c2?time=last-seven-days/sessions/5B4660E200660001278E6E93647CA557_DNE_0_v2
# Organization: TreeSnap
# Platform: android
# Application: TreeSnap
# Version: 1.4.0 (1070)
# Bundle Identifier: com.treesource
# Issue #: 7
# Issue ID: 5b465b2b6007d59fcd4084c2
# Session ID: 5B4660E200660001278E6E93647CA557_DNE_0_v2
# Date: 2018-07-11T19:57:00Z
# OS Version: 5.1.1
# Device: Premier
# RAM Free: 19%
# Disk Free: 13.5%

#0. Crashed: AsyncTask #1
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

--

Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Caused by java.lang.OutOfMemoryError: Failed to allocate a 31961100 byte allocation with 16777216 free bytes and 28MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:720)
       at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.rotateBitmap(ResolveTakenPictureAsyncTask.java:160)
       at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:92)
       at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:26)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#0. Crashed: AsyncTask #1
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by almasaeed2010** [comment]
On our BLU android device, I took more than 10 pictures without any failures. However, since the exception stack points to a problem in the script fixes an image's orientation, I've disabled that feature on devices with low RAM. We have to ask Ben to test it since no other device experienced this issue.
